### ISSUE TITLE
Economics.Skill被动技能问题

### ISSUE THREAD

**Issue by 35117** [Controllerdestiny/TShockPlugin#150]
如果手持物品购买被动技能后被动会绑定在物品上，如果继续手持该物品继续购买被动技能则不能超过“单武器绑定最大技能数量”
如果空手购买被动技能会绑定在空手上，继续空手购买被动技能不能超过“单武器绑定最大技能数量”

https://github.com/Controllerdestiny/TShockPlugin/assets/64345825/daf578c5-d40a-4f80-b5f0-dda86344ff4b

另，被动技能应该像之前版本一样设置一个上限吧

**Comment by Controllerdestiny** [comment]
已尝试修复
