### ISSUE TITLE
关于Economics.*建议（by哨兵）

### ISSUE THREAD

**Issue by 35117** [Controllerdestiny/TShockPlugin#160]
skill主动技能能否限制武器，弹幕加xy速度，触发条件能不能加冲刺（克盾、忍者装备、水晶刺客、日耀等），弹幕加个自定义持续时间
shop加个物品条件，可以做到类似合成物品的效果（不会写fishshop）

**Comment by ACaiCat** [comment]
- [ ] 弹幕加xy速度 #173 #
- [ ] 触发条件加冲刺 #168 
- [ ] 弹幕自定义持续时间 #168 
- [ ] shop物品条件 #172
