### ISSUE TITLE
DeathDrop插件问题

### ISSUE THREAD

**Issue by tangkent2** [Controllerdestiny/TShockPlugin#201]
我开启了怪物死亡随机掉落以后它报错，无论是自己写的还是默认的都一样
![Screenshot_2024-06-14-20-28-38-228_com microsoft rdc androidx](https://github.com/Controllerdestiny/TShockPlugin/assets/70203813/5618b0fb-7289-42d7-9e27-151f73af0b4f)
![Screenshot_2024-06-14-19-34-05-073_com microsoft rdc androidx](https://github.com/Controllerdestiny/TShockPlugin/assets/70203813/ea40d632-d76a-42e0-ba2a-7e34eef796b2)
![Screenshot_2024-06-14-20-29-21-575_com microsoft rdc androidx](https://github.com/Controllerdestiny/TShockPlugin/assets/70203813/ce195c11-f6af-4b57-9394-700ff34cd195)

**Comment by Controllerdestiny** [comment]
鉴定为bug

**Comment by Controllerdestiny** [comment]
修复 #202

**Comment by THEXN** [comment]
已修复：#202
