### ISSUE TITLE
Economics.WeaponPlus 强化武器插件

### ISSUE THREAD

**Issue by tangkent2** [Controllerdestiny/TShockPlugin#223]
升级蜜蜂枪的sh的时候会破图，要重开，每一次都会破图![Screenshot_2024-06-18-16-25-09-192_com.and.games505.TerrariaPaid.jpg](https://github.com/Controllerdestiny/TShockPlugin/assets/70203813/b0524270-7179-41b0-a918-3d639ed946c5)

**Comment by Controllerdestiny** [comment]
> 升级蜜蜂枪的攻速的时候会破图，要重开，每一次都会破图

这个插件不是我写的，所以下次不要带上少司命的强化武器

**Comment by Controllerdestiny** [comment]
> 升级蜜蜂枪的攻速的时候会破图，要重开，每一次都会破图

破图是什么意思

**Comment by tangkent2** [comment]
> > 升级蜜蜂枪的攻速的时候会破图，要重开，每一次都会破图
> 
> 破图是什么意思

画面消失了很大部分，变成类似天空的图案

**Comment by Controllerdestiny** [comment]
> > > 升级蜜蜂枪的攻速的时候会破图，要重开，每一次都会破图
> > 
> > 
> > 破图是什么意思
> 
> 画面消失了很大部分，变成类似天空的图案

请上传个视频

**Comment by tangkent2** [comment]
> > 升级蜜蜂枪的攻速的时候会破图，要重开，每一次都会破图
> 
> 破图是什么意思

改了，不是攻速是弹幕速度，加上截图了

**Comment by ACaiCat** [comment]
破图是炸图吗？还是说游戏画面渲染错误

**Comment by tangkent2** [comment]
> 破图是炸图吗？还是说游戏画面渲染错误

游戏画面渲染错误

**Comment by ACaiCat** [comment]
我猜是你游戏问题 （

**Comment by Controllerdestiny** [comment]
> > 破图是炸图吗？还是说游戏画面渲染错误
> 
> 游戏画面渲染错误

游戏版本问题，更换版本

**Comment by Controllerdestiny** [comment]
> > 破图是炸图吗？还是说游戏画面渲染错误
> 
> 游戏画面渲染错误


https://github.com/Controllerdestiny/TShockPlugin/assets/79201070/44d19956-b5a4-4677-80ac-e32c2f69eff1
