### ISSUE TITLE
Economics.WeaponPlus 武器强化

### ISSUE THREAD

**Issue by tangkent2** [Controllerdestiny/TShockPlugin#232]
升级后武器掉地上捡不起来了，重进后所有升级过的武器都掉地上也是捡不起来![Screenshot_2024-06-19-15-40-57-328_com.and.games505.TerrariaPaid.jpg](https://github.com/Controllerdestiny/TShockPlugin/assets/70203813/2b94e8b3-3c77-4acb-bf7f-4c8917f6d51a)

**Comment by tangkent2** [comment]
[影片在tshock群里

**Comment by Controllerdestiny** [comment]
无咎
