### ISSUE TITLE
关于Economic意见及建议 BY哨兵

### ISSUE THREAD

**Issue by 35117** [Controllerdestiny/TShockPlugin#263]
## 关于Economic.API：

- [x] 能否加击杀哪些生物不会获取经验值
- [x] 能否加生物需要什么进度之后才会掉落经验值

## 关于Economic.skill:
- [x] #314
- [x] 能否让弹幕锁定怪物攻击
- [x] 能否让弹幕优先锁定boss,血量少的敌怪
//锁定优先级？：血少boss＞boss＞血少敌怪
- [x] 能否让弹幕以锁定敌怪为点
- [x] #313
- [x] 能否加给予无敌帧 //好像有个数据表实现

## 关于Economic.RPG：
~~能否加升级获取技能~~

## 关于Economic.protectile:
~~能否加弹幕生成间隔(单位毫秒)~~
- [x] 加弹幕AI
- [x] 弹幕持续时间

## 关于进度名：
~~能否加城镇NPC在场时的进度名~~

**Comment by Controllerdestiny** [comment]
`击杀哪些生物不会获取经验值`Economics.NPC已实现

**Comment by Controllerdestiny** [comment]
- [x] 能否加击杀哪些生物不会获取经验值
- [x] 能否加生物需要什么进度之后才会掉落经验值 #266

**Comment by taffMiao** [comment]
关于Economic.skill：
- [ ] 能否记录技能使用次数，次数到了之后，执行命令（配置里面自定义该技能的使用次数，命令）

**Comment by ACaiCat** [comment]
太复杂了吧

**Comment by Controllerdestiny** [comment]
> 太复杂了吧

我也不想实现
