### ISSUE TITLE
依旧是烧饼的建议

### ISSUE THREAD

**Issue by BAsalt-Wugran-S-Xuanjiu-shao** [Controllerdestiny/TShockPlugin#264]
关于Economic.API：
1.能否加击杀哪些生物不会获取经验值
2.能否加生物需要什么进度之后才会掉落经验值

关于Economic.skill:
1.能否让弹幕在玩家发射出去的弹幕处生成
2.能否让弹幕锁定怪物攻击
3.能否让弹幕优先锁定boss,血量少的敌怪
//锁定优先级？：血少boss＞boss＞血少敌怪
4.能否让弹幕以锁定敌怪为点
5.能否加传送玩家(把玩家往X轴移动x.x,往Y轴移动x.x)
6.能否加给予无敌帧

关于Economic.RPG：
1.能否加升级获取技能

关于Economic.protectile:
1.能否加弹幕生成间隔(单位毫秒)
2.加弹幕AI
3.弹幕持续时间

关于进度名：
能否加城镇NPC在场时的进度名

**Comment by ACaiCat** [comment]
补到原议题下面
