### ISSUE TITLE
关于tshock原版超管头衔无法和等级共存

### ISSUE THREAD

**Issue by BAsalt-Wugran-S-Xuanjiu-shao** [Controllerdestiny/TShockPlugin#279]
今天有一个开服小白突然来问了这个问题
大概就是超管头衔无法和等级头衔共存，哪怕在配置文件改了头衔位置也没有应
![Image_1720503765617](https://github.com/Controllerdestiny/TShockPlugin/assets/161994770/f65e811c-9bbc-4203-a910-2c7945ea9af0)

改了之后
![Image_1720503751213](https://github.com/Controllerdestiny/TShockPlugin/assets/161994770/9f6c9962-b803-492e-9515-e94042a17849)
![Image_1720503748375](https://github.com/Controllerdestiny/TShockPlugin/assets/161994770/e165ac83-1173-46a7-ba7a-2eb3add91ddd)
![Image_1720503767679](https://github.com/Controllerdestiny/TShockPlugin/assets/161994770/46a3de1b-9227-4c22-969d-014e42bb550c)

**Comment by Controllerdestiny** [comment]
#280 此pr添加了一个权限`economics.rpg.chat`来解决这个问题

**Comment by 1242509682** [comment]
冲击派系的问题，把冲击派系配置项里的聊天格式关了就好了，这个插件的聊天格式与EC的RPG存在冲突。
