### ISSUE TITLE
计划书插件

### ISSUE THREAD

**Issue by tangkent2** [Controllerdestiny/TShockPlugin#281]
计划书插件在后台疯狂刷屏![Screenshot_2024-07-09-17-59-46-536_com.microsoft.rdc.androidx.jpg](https://github.com/Controllerdestiny/TShockPlugin/assets/70203813/35b846c2-4f2f-4f22-9fb9-2e7e466c6be8)

**Comment by 1242509682** [comment]
怀疑纯属个人原因，请检查清楚再反馈，插件发布这么久只有你一个人遇到了。

**Comment by 1242509682** [comment]
怀疑纯属个人原因，请检查清楚再反馈，插件发布这么久只有你一个人遇到了。

**Comment by 1242509682** [comment]
怀疑纯属个人原因，请检查清楚再反馈，插件发布这么久只有你一个人遇到了。必要的时候：关闭服务器删掉现有配置文件让其自动创建最新的配置文件。

**Comment by ACaiCat** [comment]
我猜是因为你配置哪里写了个石巨人，插件识别不了，还有下次提交Issue不要只发报错，插件配置也一起发
