### ISSUE TITLE
关于Economic.Skill技能装备限制的bug

### ISSUE THREAD

**Issue by 35117** [Controllerdestiny/TShockPlugin#292]
https://github.com/user-attachments/assets/8a6910d6-9d06-4016-8734-4accef33dd10

以上是演示视频
具体描述：因为技能要限制某物品才能使用，因此使用了装备条件
然而会有刷物品/物品消失的情况
 {
            "背包物品": false,
            "装备饰品": false,
            "手持物品": false,
            "是否消耗": false,
            "物品ID": 4057,
            "数量": 0,
            "前缀": 0
          }
这样填的话导致只背包中有即可使用，如果手持物品开启true则只能在对应物品使用，但是当在背包中拿起限制的物品如4057时，会有概率在原位置刷出来一个一样的物品，是否消耗似乎没用，是false或true的情况下，数量填为1都会导致背包内所有该物品消失。背包物品true或false似乎也没用，视频如果没法看的话记得回复

**Comment by Controllerdestiny** [comment]
#296 修复了一下

**Comment by Controllerdestiny** [comment]
如有问题重开此issue
