### ISSUE TITLE
关于计划书的建议

### ISSUE THREAD

**Issue by BAsalt-Wugran-S-Xuanjiu-shao** [Controllerdestiny/TShockPlugin#320]
想要增加一个功能，让重置的时候不是直接删除地图
是把地图复制到指定的文件夹，这样可以防止手残，还有反悔的机会，也可以防止管理突然造反（）

**Comment by Controllerdestiny** [comment]
这是怎么，被造反了吗。

**Comment by 1242509682** [comment]
你不如好好看看自己配置文件底下有没有，从1.0.5就已经实现了

> 想要增加一个功能，让重置的时候不是直接删除地图 是把地图复制到指定的文件夹，这样可以防止手残，还有反悔的机会，也可以防止管理突然造反（）
