### ISSUE TITLE
Economic.skill建议

### ISSUE THREAD

**Issue by TKFTshaobing** [Controllerdestiny/TShockPlugin#339]
1.能否让主动触发默认为使用物品时触发，而如果需要限制在一个物品上才能使用时，则在物品条件中写入                                                                2.锁定敌怪加锁定多个敌怪

**Comment by ACaiCat** [comment]
话说你们RPG这么复杂的吗

**Comment by Controllerdestiny** [comment]
> 话说你们RPG这么复杂的吗

这哥们一天一个issue我已经开摆了，什么时候想起来什么时候写。

**Comment by ACaiCat** [comment]
建议
![image](https://github.com/user-attachments/assets/7c0803a9-351f-4b0d-b82c-d79e5a393bd3)

**Comment by Controllerdestiny** [comment]
有道理，他这俩需求确实没法搞，主动触发本来就是使用物品时候触发。

**Comment by Controllerdestiny** [comment]
草点错了
