### ISSUE TITLE
This is very good because there is a large list of plugins, but unfortunately I don't understand Chinese, do you have an English version of the source?

### ISSUE THREAD

**Issue by Hexagonforce12** [Controllerdestiny/TShockPlugin#346]

**Comment by ACaiCat** [comment]
It's so hard for us to translate so much plugins,but I will make a English version of the README to let you know the functions of all plugins.And than you can tell us the plugins you want,and I will translate them by AI.

**Comment by Hexagonforce12** [comment]
Ok
