### ISSUE TITLE
RPG插件整合包玩家前缀不显示

### ISSUE THREAD

**Issue by qiren666** [Controllerdestiny/TShockPlugin#355]
权限给了，插件配置表也检查过了
[Image_1722251508627](https://github.com/user-attachments/assets/cae4807e-2c52-400c-835e-069a512dd4db)
[Image_1722251506741](https://github.com/user-attachments/assets/a45cad51-a1b3-427b-ac1a-7e1c39cc7c5c)
一开始我以为自己的配置表有问题，结果后面改用了羽学配置表玩家的前缀依然不显示，检查了蛮多遍了

**Comment by Controllerdestiny** [comment]
咋解释的呢？economics.rpg.chat 权限是，显示原生消息的问题权限，把这个权限删了就好了。
