### ISSUE TITLE
添加发言长度限制功能

### ISSUE THREAD

**Issue by TskimiSeiran** [Controllerdestiny/TShockPlugin#374]
## 检查表
- [x] 我已经阅读[发ISSUE必看](https://github.com/Controllerdestiny/TShockPlugin/issues/352)
- [x] 我已确保所有信息都填写完整
- [x] 我已确我提交的功能对大部分服主有益

## 插件信息
* 插件名:发言长度限制
* 新功能简述:由于PE端接收到太长的信息会崩溃客户端，设定一个消息最大长度以阻止恶意玩家利用超长信息让PE端玩家崩溃
  
## 新功能详细

- [x] 添加发言长度限制
- [x] 当玩家的发言长度超过了设定的值，发送信息后插件会阻止它
- [x] .....

**Comment by Controllerdestiny** [comment]
#375 实现到ServerTools插件里了
