### ISSUE TITLE
For Challenger plugins

### ISSUE THREAD

**Issue by Hexagonforce12** [Controllerdestiny/TShockPlugin#423]
### 已阅须知

- [X] 是

### 功能有益

- [X] 是

### 插件名字

Challenger

### 需要什么功能?

please fix the text to a bug like that, and please update it so we can create own custom armor effects and custom bosses or npcs
![IMG_20240829_224435](https://github.com/user-attachments/assets/66d678c3-4619-4468-8640-713476258793)

**Comment by sgkoishi** [comment]
This is not a 'bug': it's your font that does not contain the glyph for those characters. You can translate the plugin to your language, or switch to a font that can show these.

**Comment by Hexagonforce12** [comment]
it looks like it might be chinese but there is no tshock chinese font

**Comment by sgkoishi** [comment]
The font is only used on the client side. For PC the default font uses [Source Han Sans](https://en.wikipedia.org/wiki/Source_Han_Sans) for the Chinese characters, but for mobile players you are out of luck. You need to analyze the game, find out where the embedded font is and create a font that contains Chinese characters.

A much simpler solution is to translate the plugin to your language.

**Comment by Hexagonforce12** [comment]
I dont know how to translate plugin

**Comment by sgkoishi** [comment]
Now there is a [`template.pot`](https://github.com/UnrealMultiple/TShockPlugin/blob/master/Challenger/i18n/template.pot) with translatable texts inside. You can use translation tools like [Poedit](https://poedit.net/) to add translation. You can submit the translations via git or just upload it here.

**Comment by Controllerdestiny** [comment]
我们已经开始做翻译工作了。
