### ISSUE TITLE
bro, what is QQ group? like this QQ群(232109072)

### ISSUE THREAD

**Issue by Hexagonforce12** [Controllerdestiny/TShockPlugin#47]

**Comment by 1242509682** [comment]
This is a social software developed in China. Typically, we upload the plugins we've written to groups within this application. It's called QQ. You can take a look at this:
[github]https://github.com/Pryaxis/TShock/blob/general-devel/README_cn.md
The "QQ Group" mentioned at the very bottom is our primary Tshock communication community in China.

**Comment by Hexagonforce12** [comment]
Ooh..I've tried to create a QQ account but I can't. I've also downloaded the QQ application but I can't use it because I don't understand Chinese.

**Comment by Hexagonforce12** [comment]
I'm mobile bro

**Comment by Hexagonforce12** [comment]
![IMG_20240424_032057](https://github.com/Controllerdestiny/TShockPlugin/assets/109804725/119d7871-634c-495c-afe9-20978aa11cc5)
Can you help me scan the barcode?

**Comment by Controllerdestiny** [comment]
bro, I tried scanning but it jumped to Download。
You'll just have to translate。
QQ The international version has been taken down

**Comment by Hexagonforce12** [comment]
The QQ mobile application is in Chinese and there are no other languages. I've also watched the tutorial and it turns out can't create an account on the QQ application if it's not a Chinese number.

**Comment by Controllerdestiny** [comment]
What you want to know about using QQ

**Comment by Hexagonforce12** [comment]
I want to join a QQ group, like a group that discusses server plugins or something else

**Comment by Controllerdestiny** [comment]
This is bad. We can't help you.

**Comment by Controllerdestiny** [comment]
Recommend you two forums about Tshock.
https://www.bbstr.net But he's about to be shut down
https://trhub.cn/ It's new but not much in the way of resources

**Comment by Hexagonforce12** [comment]
Bruh,are you Chinese?

**Comment by Controllerdestiny** [comment]
yes
