### ISSUE TITLE
[BUG] : ItemDecoPlugin

### ISSUE THREAD

**Issue by itsFrankV22** [Controllerdestiny/TShockPlugin#596]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

ItemDecoplugin

### 系统 | System

Windows

### 发生了什么? | What happened?

CH 
您好，我允许您根据自己的喜好修改我的插件，但有一个问题，当使用 LazyAPI 时，如果浮动文本没有出现在左侧稍远的地方，则浮动文本不会出现在靠近玩家的位置，我知道这是第一次你使用API​​，但我祝你好运，如果有必要，我允许你修改我的插件，以提高API的功能，对我来说没有问题，你可以自由发挥，祝你好运

EN
Hello, I allowed you to modify my plugin to your liking but there is a problem, when using LazyAPI the floating texts do not appear close to the player if they do not appear a little far to the left, I know it is the first time you use the api but I wish you good luck, I allow you to modify my plugin as much as you want if necessary to improve the capabilities of the api, for me there is no problem you have free rein, I wish you luck

### 如何复现 | How to reproduce

N/A

### 期望的结果? | Expected result?

CH
更换武器时的浮动文本会在玩家上方运行，而不是在侧面

EN
That the floating text when changing weapons runs above the player and not a little to the side

### 文本日志 | Text log

```shell
N/A
```

### 控制台日志 | Console log

```shell
N/A
```

**Comment by Controllerdestiny** [comment]
能不能提供一下截图

**Comment by Controllerdestiny** [comment]
你可以使用你得母语

**Comment by Controllerdestiny** [comment]
我们会使用翻译器阅读
