### ISSUE TITLE
Yo bro, what plugin is this, is this just released?

### ISSUE THREAD

**Issue by Hexagonforce12** [Controllerdestiny/TShockPlugin#8]

**Comment by Controllerdestiny** [comment]
This is a collection of plug-ins in the warehouse, the warehouse plug-ins in China is not considered new plug-ins, if you can not read Chinese please use the translator.

**Comment by Hexagonforce12** [comment]
Oh ok,btw do you know where the list Chinese plugins?

**Comment by Controllerdestiny** [comment]
https://www.bbstr.net/
