### ISSUE TITLE
AutoBroadcast中{player}占位符问题

### ISSUE THREAD

**Issue by 35117** [Controllerdestiny/TShockPlugin#83]
![N_~S@KHRTG7PJZXU _BQK)H](https://github.com/Controllerdestiny/TShockPlugin/assets/64345825/f47fcb54-3ca2-4344-8df6-9d577bc02972)
![_SP`XBU20OH 0E~%_(QSUU2](https://github.com/Controllerdestiny/TShockPlugin/assets/64345825/a5f201eb-f722-4875-a781-b05fb29df479)
**如图，之前的玩家触发以后{player}就绑定在他身上，后来触发的玩家依旧是之前的
reload后依旧是最开始的玩家
配置事例**
![image](https://github.com/Controllerdestiny/TShockPlugin/assets/64345825/eda7e973-6f5a-41bc-bed5-3937d7638546)

**Comment by Controllerdestiny** [comment]
已修复 [82067d96990d37cc980fa8b380dfe7322e6e2c87](https://github.com/Controllerdestiny/TShockPlugin/commit/82067d96990d37cc980fa8b380dfe7322e6e2c87)
