### ISSUE TITLE
AutoBroadcat关于触发组建议

### ISSUE THREAD

**Issue by 35117** [Controllerdestiny/TShockPlugin#84]
**能否使配置中触发组为空时使所有组都可触发
目前情况为，必须写上某组，该组才能触发
如果需要全部组触发必须挨个添加**
![%WQ~JES@%FD03K6(GLW%UL](https://github.com/Controllerdestiny/TShockPlugin/assets/64345825/b8e22edf-5a54-4755-b54f-9ad09a253612)
![%H{1$~Q81 DQ@TS5UOSO5MD](https://github.com/Controllerdestiny/TShockPlugin/assets/64345825/584aa5a0-3a14-44d5-863b-bfbcc92ed7e8)

**Comment by Controllerdestiny** [comment]
此插件早已实现触发组使用*符号代表所有组
```json
{
  "广播列表": [
    {
      "名称": "示例广播",
      "是否启用": true,
      "消息列表": [
        "{player}"
      ],
      "颜色RGB": [
        255.0,
        0.0,
        0.0
      ],
      "间隔时间": 300,
      "延迟时间": 60,
      "触发区域": [],
      "区域触发器": "none",
      "组": [
        "*"
      ],
      "触发词": [
        "test"
      ],
      "是否触发整个组": false
    }
  ]
}
```

**Comment by 35117** [comment]
> 此插件早已实现触发组使用*符号代表所有组
> 
> ```json
> {
>   "广播列表": [
>     {
>       "名称": "示例广播",
>       "是否启用": true,
>       "消息列表": [
>         "{player}"
>       ],
>       "颜色RGB": [
>         255.0,
>         0.0,
>         0.0
>       ],
>       "间隔时间": 300,
>       "延迟时间": 60,
>       "触发区域": [],
>       "区域触发器": "none",
>       "组": [
>         "*"
>       ],
>       "触发词": [
>         "test"
>       ],
>       "是否触发整个组": false
>     }
>   ]
> }
> ```

好的，那就没问题了，感谢解答
